"""
Competency definitions for MT (L11 | Band 4) and GET (L08T | Band 5) roles.
Used by views and templates to render survey forms.
"""

MT_COMPETENCIES = {
    'pre_post': [
        {'code': 'T1', 'name': 'EV/PHEV Business Understanding', 'domain': 'Technical', 'desired': 2, 'safety': False},
        {'code': 'T2', 'name': 'Safety & Compliance Leadership [NON-NEG]', 'domain': 'Safety', 'desired': 2, 'safety': True},
        {'code': 'T3', 'name': 'Manufacturing Ops & Value Chain', 'domain': 'Technical', 'desired': 1, 'safety': False},
        {'code': 'T4', 'name': 'Data Analytics & Digital Decisions', 'domain': 'Technical', 'desired': 2, 'safety': False},
        {'code': 'T5', 'name': 'Financial Literacy & P&L', 'domain': 'Technical', 'desired': 2, 'safety': False},
        {'code': 'T6', 'name': 'Function-Specific Technical', 'domain': 'Technical', 'desired': 2, 'safety': False},
        {'code': 'B1', 'name': 'Commercial Acuity & Business Perspective', 'domain': 'Behavioural', 'desired': 2, 'safety': False},
        {'code': 'B2', 'name': 'Entrepreneurial Sensing & Opportunity', 'domain': 'Behavioural', 'desired': 2, 'safety': False},
        {'code': 'B3', 'name': 'Change Leadership & Agility', 'domain': 'Behavioural', 'desired': 2, 'safety': False},
        {'code': 'B4', 'name': 'People Growth & Talent Cultivation', 'domain': 'Behavioural', 'desired': 2, 'safety': False},
        {'code': 'B5', 'name': 'Ownership & Proactive Accountability', 'domain': 'Behavioural', 'desired': 3, 'safety': False},
        {'code': 'L1', 'name': 'Strategic Thinking', 'domain': 'Leadership', 'desired': 2, 'safety': False},
        {'code': 'L2', 'name': 'Stakeholder Management & Presence', 'domain': 'Leadership', 'desired': 3, 'safety': False},
        {'code': 'L3', 'name': 'Cross-Functional Leadership', 'domain': 'Leadership', 'desired': 2, 'safety': False},
        {'code': 'L4', 'name': 'Communication & Executive Storytelling', 'domain': 'Leadership', 'desired': 3, 'safety': False},
        {'code': 'L5', 'name': 'Team Leadership & Performance Mgmt', 'domain': 'Leadership', 'desired': 2, 'safety': False},
        {'code': 'L6', 'name': 'Coaching Mindset', 'domain': 'Leadership', 'desired': 2, 'safety': False},
        {'code': 'L7', 'name': 'Resilience & Ambiguity Tolerance', 'domain': 'Leadership', 'desired': 2, 'safety': False},
    ],
    'bars_technical': [
        {
            'code': 'T1', 'name': 'EV/PHEV Business', 'safety': False,
            'L1': 'Cannot explain EV commercial case; wrong terminology with stakeholders',
            'L2': 'Knows product portfolio; needs coaching on technology-commercial linkages',
            'L3': 'Explains PHEV advantages to dealers/investors; links tech decisions to commercial outcomes',
            'L4': 'Presents tech strategy to senior leadership; leads competitive analysis',
        },
        {
            'code': 'T2', 'name': 'Safety Leadership ⚠', 'safety': True,
            'L1': 'Does not enforce safety in own team; bypasses protocols',
            'L2': 'Complies personally but does not role-model safety culture',
            'L3': 'Ensures team compliance; addresses unsafe behaviour; leads safety briefings',
            'L4': 'Designs compliance systems; drives safety culture as leadership priority',
        },
        {
            'code': 'T3', 'name': 'Mfg Ops & Value Chain', 'safety': False,
            'L1': 'Cannot describe manufacturing value chain; unaware of interdependencies',
            'L2': 'Understands basic flow; contributes to ops reviews with prompting',
            'L3': 'Analyses OEE data; identifies bottlenecks; participates meaningfully in ops reviews',
            'L4': 'Leads ops discussions; owns OEE improvement; drives value chain redesign',
        },
        {
            'code': 'T4', 'name': 'Data & Digital', 'safety': False,
            'L1': 'No data use in decisions; opinions without evidence; avoids dashboards',
            'L2': 'Uses Excel for basics; reads dashboards; asks data questions when prompted',
            'L3': 'Builds pivot analysis; creates dashboards; presents data-driven cases independently',
            'L4': 'Architects analytics for function; designs predictive models',
        },
        {
            'code': 'T5', 'name': 'Financial Literacy', 'safety': False,
            'L1': 'Cannot read P&L; makes decisions without cost consideration',
            'L2': 'Reads P&L with guidance; understands EBITDA; participates in budget reviews',
            'L3': 'Analyses cost variances; builds ROI cases; manages small budgets accurately',
            'L4': 'Leads dept budget prep; presents financial analysis to CFO/CHRO',
        },
        {
            'code': 'T6', 'name': 'Function-Specific', 'safety': False,
            'L1': 'No knowledge of function systems, processes or regulatory requirements',
            'L2': 'Understands structure; performs basic tasks under supervision',
            'L3': 'Manages function deliverables independently; advises colleagues on function matters',
            'L4': 'Designs frameworks; advises senior leadership; drives function strategy',
        },
    ],
    'bars_behavioural': [
        {
            'code': 'B1', 'name': 'Commercial Acuity', 'safety': False,
            'L1': 'Cannot connect work to business outcomes; no ROI consideration in proposals',
            'L2': 'Understands how JSW makes money; occasionally frames proposals commercially',
            'L3': 'Analyses situations with commercial lens; builds ROI cases without finance input',
            'L4': 'Shapes business model discussions; advises function heads; anticipates market shifts',
        },
        {
            'code': 'B2', 'name': 'Entrepreneurial Drive', 'safety': False,
            'L1': 'No initiative beyond assigned tasks; waits to be told what to do',
            'L2': 'Spots improvements in own area; raises ideas when asked',
            'L3': 'Proactively identifies cross-functional opportunities; pilots new approaches',
            'L4': 'Identifies business white-spaces; builds cases; champions new ventures',
        },
        {
            'code': 'B3', 'name': 'Change Leadership', 'safety': False,
            'L1': 'Actively resists change; undermines change efforts in team',
            'L2': 'Adapts personally; does not communicate change rationale to team',
            'L3': 'Communicates change rationale clearly; addresses resistance empathetically',
            'L4': 'Designs ADKAR plans; manages complex multi-stakeholder transitions',
        },
        {
            'code': 'B4', 'name': 'People Growth', 'safety': False,
            'L1': "No interest in others' development; no feedback; no development plans",
            'L2': 'Supports peers when asked; shares knowledge occasionally',
            'L3': 'Coaches reports with structured feedback; every direct report has written IDP',
            'L4': 'Identifies HiPos; builds succession plans; sponsors high-potentials',
        },
        {
            'code': 'B5', 'name': 'Ownership & Accountability', 'safety': False,
            'L1': 'No follow-through without reminders; blames systems/people',
            'L2': 'Delivers on tasks; informs manager; attributes setbacks partly to external factors',
            'L3': 'Proactively identifies adjacent tasks; resolves blockers independently',
            'L4': 'Creates ownership culture; eliminates blame; builds accountability systems',
        },
    ],
    'bars_leadership': [
        {
            'code': 'L1', 'name': 'Strategic Thinking', 'safety': False,
            'L1': 'Focuses only on immediate task; cannot articulate JSW strategy',
            'L2': 'Understands strategy; occasionally links work to objectives with prompting',
            'L3': 'Links own work to strategic objectives; prioritises by business impact',
            'L4': 'Defines function strategy; identifies strategic risks; advises CHRO/Board',
        },
        {
            'code': 'L2', 'name': 'Stakeholder Mgmt.', 'safety': False,
            'L1': 'Ignores stakeholders; surprises management with issues',
            'L2': 'Communicates professionally; manages expectations reactively',
            'L3': 'Manages expectations proactively; pre-aligns key stakeholders before major decisions',
            'L4': 'Navigates complex stakeholder landscapes; resolves conflicts at senior level',
        },
        {
            'code': 'L3', 'name': 'Cross-Func. Leadership', 'safety': False,
            'L1': 'Creates silos; other functions find difficult to work with',
            'L2': 'Works cooperatively; shares information when asked',
            'L3': 'Facilitates cross-functional problem solving; drives collective outcomes',
            'L4': 'Leads cross-functional task forces; designs matrix governance',
        },
        {
            'code': 'L4', 'name': 'Exec. Storytelling', 'safety': False,
            'L1': 'Communications unclear; presentations unprepared; outputs need rework',
            'L2': 'Communicates clearly; basic presentation skills; professional interactions',
            'L3': 'Presents structured business cases; adapts communication for audience',
            'L4': 'Delivers Executive presentations; shapes org narratives; influences externally',
        },
        {
            'code': 'L5', 'name': 'Team Leadership', 'safety': False,
            'L1': 'No clarity on team expectations; no feedback; team unaware of performance',
            'L2': 'Sets expectations verbally; gives informal feedback reactively',
            'L3': 'Clear written targets; monthly 1:1s with SBI feedback; no one surprised at review',
            'L4': 'Designs performance systems; manages underperformance; builds high-performance culture',
        },
        {
            'code': 'L6', 'name': 'Coaching Mindset', 'safety': False,
            'L1': 'Tells rather than coaches; impatient with team learning',
            'L2': 'Occasionally asks questions rather than directing',
            'L3': 'Uses GROW model in 1:1s; resists giving answers; creates psychological safety',
            'L4': 'Builds coaching culture; trains other managers; creates mentoring architecture',
        },
        {
            'code': 'L7', 'name': 'Resilience', 'safety': False,
            'L1': 'Visibly panics; escalates everything; team loses confidence',
            'L2': 'Manages personal stress; maintains basic composure',
            'L3': 'Maintains composure in pressure; helps team stay focused; sound decisions under uncertainty',
            'L4': 'Leads calmly through crises; develops scenario options; coaches others on resilience',
        },
    ],
}

GET_COMPETENCIES = {
    'pre_post': [
        {'code': 'T1', 'name': 'EV/PHEV Systems Understanding', 'domain': 'Technical', 'desired': 2, 'safety': False},
        {'code': 'T2', 'name': 'Safety & HV Compliance [NON-NEG]', 'domain': 'Safety', 'desired': 3, 'safety': True},
        {'code': 'T3', 'name': 'Manufacturing Process Engineering', 'domain': 'Technical', 'desired': 2, 'safety': False},
        {'code': 'T4', 'name': 'Quality & IATF 16949', 'domain': 'Technical', 'desired': 2, 'safety': False},
        {'code': 'T5', 'name': 'Lean / Kaizen / 5S', 'domain': 'Technical', 'desired': 2, 'safety': False},
        {'code': 'T6', 'name': 'Digital Tools (DELMIA/MES/PLM)', 'domain': 'Technical', 'desired': 2, 'safety': False},
        {'code': 'B1', 'name': 'Customer-Centricity in Quality', 'domain': 'Behavioural', 'desired': 2, 'safety': False},
        {'code': 'B2', 'name': 'Agile Execution & Adaptability', 'domain': 'Behavioural', 'desired': 2, 'safety': False},
        {'code': 'B3', 'name': 'Goal-Anchored Performance Drive', 'domain': 'Behavioural', 'desired': 2, 'safety': False},
        {'code': 'B4', 'name': 'Kaizen Mindset & Curiosity', 'domain': 'Behavioural', 'desired': 2, 'safety': False},
        {'code': 'B5', 'name': 'Ingenious Problem Solving', 'domain': 'Behavioural', 'desired': 2, 'safety': False},
        {'code': 'B6', 'name': 'JSW Values & Cultural Fit', 'domain': 'Behavioural', 'desired': 2, 'safety': False},
        {'code': 'L1', 'name': 'Ownership & Accountability', 'domain': 'Leadership', 'desired': 2, 'safety': False},
        {'code': 'L2', 'name': 'Learning Agility', 'domain': 'Leadership', 'desired': 2, 'safety': False},
        {'code': 'L3', 'name': 'Cross-Functional Collaboration', 'domain': 'Leadership', 'desired': 2, 'safety': False},
        {'code': 'L4', 'name': 'Technical Communication', 'domain': 'Leadership', 'desired': 2, 'safety': False},
        {'code': 'L5', 'name': 'Adaptability to Change', 'domain': 'Leadership', 'desired': 2, 'safety': False},
    ],
    'bars_technical': [
        {
            'code': 'T1', 'name': 'EV/PHEV Systems', 'safety': False,
            'L1': 'Cannot name EV components; unaware of BEV vs ICE',
            'L2': 'Names components; needs guidance on all EV procedures',
            'L3': 'Follows all EV SOPs without prompts; identifies HV zones independently',
            'L4': 'Trains peers; improves SOPs from field experience',
        },
        {
            'code': 'T2', 'name': 'Safety & HV ⚠', 'safety': True,
            'L1': 'Entered HV zone without PPE; skipped LOTO; no near-miss report',
            'L2': 'Wears PPE when reminded; occasionally forgets HV isolation',
            'L3': 'Follows ALL HV protocols unprompted; reports near-misses same day',
            'L4': 'Coaches peers on HV safety; leads safety observations',
        },
        {
            'code': 'T3', 'name': 'Manufacturing Process', 'safety': False,
            'L1': 'Cannot follow work instruction independently; high deviation/scrap',
            'L2': 'Follows WI with supervision; needs prompting for NCR escalation',
            'L3': 'Operates correctly every shift; records all deviations in MES within 30 min',
            'L4': 'Updates WIs; coaches technicians; identifies bottlenecks proactively',
        },
        {
            'code': 'T4', 'name': 'Quality & IATF', 'safety': False,
            'L1': 'Passes non-conforming parts; skips inspection checklist',
            'L2': 'Checks sometimes; occasional NCR escape; needs reminders',
            'L3': 'Full inspection every time; self-catches defects before release; raises NCR independently',
            'L4': 'Identifies systemic issues; initiates CAPA unprompted',
        },
        {
            'code': 'T5', 'name': 'Lean / Kaizen / 5S', 'safety': False,
            'L1': 'Workstation in disorder; 5S <2/5; no Kaizen ideas submitted',
            'L2': '5S when reminded; rare Kaizen ideas; needs direction',
            'L3': '5S ≥4/5 consistently; min 1 implemented Kaizen/quarter',
            'L4': 'Facilitates Kaizen events; coaches peers; quantifies results',
        },
        {
            'code': 'T6', 'name': 'Digital Tools', 'safety': False,
            'L1': 'Does not use MES; avoids digital WIs; data entries missing',
            'L2': 'Enters MES when reminded; follows digital WI with guidance',
            'L3': 'Uses all digital tools independently; MES entries complete every shift',
            'L4': 'Creates DELMIA WIs; trains peers; pulls MES analytics for improvement',
        },
    ],
    'bars_behavioural': [
        {
            'code': 'B1', 'name': 'Customer-Centricity', 'safety': False,
            'L1': 'Releases non-conforming parts under pressure; ignores downstream impact',
            'L2': 'Checks sometimes; does not consistently think about customer impact',
            'L3': 'Holds back work when unsure; zero-escape mindset even under schedule pressure',
            'L4': 'Designs quality checks with customer satisfaction as primary criterion',
        },
        {
            'code': 'B2', 'name': 'Agile Execution', 'safety': False,
            'L1': 'Refuses new tasks when methods change; unproductive during disruption',
            'L2': 'Completes tasks under stable conditions; struggles when priorities shift',
            'L3': 'Adapts rapidly; maintains quality during disruptions; flags impact proactively',
            'L4': 'Resequences work to maximise output; helps peers adapt',
        },
        {
            'code': 'B3', 'name': 'Goal-Anchored Drive', 'safety': False,
            'L1': 'Unaware of daily targets; needs constant follow-up',
            'L2': 'Knows targets but does not track; needs reminders to course-correct',
            'L3': 'Tracks output vs target throughout shift; self-corrects; flags blockers same day',
            'L4': 'Sets micro-goals; connects personal targets to plant KPIs',
        },
        {
            'code': 'B4', 'name': 'Kaizen Mindset', 'safety': False,
            'L1': "Views problems as someone else's; never questions processes",
            'L2': 'Participates in Kaizen when asked; rare improvement ideas',
            'L3': 'Initiates A3 for recurring issues; submits implemented Kaizen ideas quarterly',
            'L4': 'Facilitates Kaizen events; mentors peers; quantifies results monthly',
        },
        {
            'code': 'B5', 'name': 'Problem Solving', 'safety': False,
            'L1': 'Applies only obvious solutions; repeats failed approaches',
            'L2': 'Tries new approaches occasionally; does not explore beyond obvious',
            'L3': 'Applies 5-Why beyond symptoms; validates unconventional solutions before deploying',
            'L4': 'Facilitates creative problem-solving; creates space for non-standard ideas',
        },
        {
            'code': 'B6', 'name': 'JSW Values', 'safety': False,
            'L1': 'Cannot articulate JSW Values; behaviour inconsistent with values',
            'L2': 'Can articulate values; applies them inconsistently',
            'L3': 'Lives values daily; 2+ peers recognise as values-exemplar; de-escalates via values',
            'L4': 'Champions values in team; addresses violations; culture carrier for new joiners',
        },
    ],
    'bars_leadership': [
        {
            'code': 'L1', 'name': 'Ownership', 'safety': False,
            'L1': 'Does not follow through without reminders; blames others',
            'L2': 'Completes tasks; needs occasional follow-up',
            'L3': 'Delivers without reminders; flags blockers same day; proposes solutions',
            'L4': 'Takes on tasks beyond role; drives closure without escalation',
        },
        {
            'code': 'L2', 'name': 'Learning Agility', 'safety': False,
            'L1': 'Resists new methods; does not complete training; applies nothing',
            'L2': 'Completes training when mandatory; applies after 4+ weeks',
            'L3': 'Seeks feedback proactively; applies learning within 2 weeks; shares insights',
            'L4': 'Identifies own needs; builds learning networks; creates resources for others',
        },
        {
            'code': 'L3', 'name': 'Cross-Func. Collab.', 'safety': False,
            'L1': 'Hoards information; creates friction at functional boundaries',
            'L2': 'Responds to requests when asked; does not proactively share',
            'L3': 'Proactively shares info; facilitates cross-dept problem solving; zero silo',
            'L4': 'Leads cross-functional initiatives; resolves inter-team conflicts',
        },
        {
            'code': 'L4', 'name': 'Technical Comms.', 'safety': False,
            'L1': 'Shift reports incomplete/illegible; fails to escalate deviations',
            'L2': 'Reports major events; misses details; occasional late escalation',
            'L3': 'Reports complete, accurate, on time every shift; deviations escalated with root cause same day',
            'L4': 'Sets reporting standard; trains peers; drives operational decisions via comms',
        },
        {
            'code': 'L5', 'name': 'Adaptability', 'safety': False,
            'L1': 'Actively resists new SOPs; publicly complains; slows others',
            'L2': 'Accepts change when instructed; does not openly resist but drags',
            'L3': 'Adopts new SOPs quickly; helps 2+ peers adapt; communicates rationale',
            'L4': 'Becomes change champion; coaches resistant peers with empathy',
        },
    ],
}

HAPPY_SHEET_QUESTIONS = [
    ('Q1', 'Content relevant to my role'),
    ('Q2', 'Pitched at right level for my grade'),
    ('Q3', 'Trainer had strong subject expertise'),
    ('Q4', 'Materials were high quality'),
    ('Q5', 'I could ask questions freely'),
    ('Q6', 'Duration was appropriate'),
    ('Q7', 'I feel more confident after this training'),
    ('Q8', 'Training had practical JSW Motors examples'),
    ('Q9', 'I know how to apply this within 2 weeks'),
    ('Q10', 'I would recommend this to a colleague'),
]

SURVEY_META = {
    'happy-sheet': {
        'title': 'Happy Sheet',
        'subtitle': 'Level 1 — Reaction Survey',
        'icon': '😊',
        'color': '#28a745',
        'description': 'Complete within 24 hrs of training. Target: Average ≥ 4.0/5.0 | NPS ≥ 8/10',
    },
    'pre-assessment': {
        'title': 'Pre-Training Assessment',
        'subtitle': 'Level 2 — Competency Baseline',
        'icon': '📋',
        'color': '#007bff',
        'description': 'Both candidate AND manager rate independently. Divergence > 1 pt → HR-BP calibration.',
    },
    'post-assessment': {
        'title': 'Post-Training Assessment',
        'subtitle': 'Level 2 — Post-Training Evaluation',
        'icon': '📊',
        'color': '#17a2b8',
        'description': 'ΔScore = Post − Pre. Target: ΔScore ≥ +1.0 per competency.',
    },
    'bars-technical': {
        'title': 'BARS Technical Evaluation',
        'subtitle': 'Level 3 — Behavioural Observation (Technical)',
        'icon': '⚙️',
        'color': '#fd7e14',
        'description': 'Observe 5–7 working days before scoring. Day 30/60/90 post-training. Target: ≥ 3.0 average.',
    },
    'bars-behavioural': {
        'title': 'BARS Behavioural Evaluation',
        'subtitle': 'Level 3 — Behavioural Observation (Behavioural)',
        'icon': '🎯',
        'color': '#6f42c1',
        'description': 'Observe 5–7 working days before scoring. Day 30/60/90 post-training. Target: ≥ 3.0 average.',
    },
    'bars-leadership': {
        'title': 'BARS Leadership Evaluation',
        'subtitle': 'Level 3 — Behavioural Observation (Leadership)',
        'icon': '🏆',
        'color': '#dc3545',
        'description': 'Observe 5–7 working days before scoring. Day 30/60/90 post-training. Target: ≥ 3.0 average.',
    },
}
