from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HappySheetResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MT', 'MT (L11 | Band 4)'), ('GET', 'GET (L08T | Band 5)')], max_length=10)),
                ('employee_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('program_name', models.CharField(max_length=300)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('competency', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(blank=True, max_length=100)),
                ('trainer', models.CharField(blank=True, max_length=200)),
                ('q1', models.IntegerField()),
                ('q2', models.IntegerField()),
                ('q3', models.IntegerField()),
                ('q4', models.IntegerField()),
                ('q5', models.IntegerField()),
                ('q6', models.IntegerField()),
                ('q7', models.IntegerField()),
                ('q8', models.IntegerField()),
                ('q9', models.IntegerField()),
                ('q10', models.IntegerField()),
                ('nps_score', models.IntegerField()),
                ('open_feedback', models.TextField(blank=True)),
                ('supervisor', models.CharField(blank=True, max_length=200)),
                ('hr_bp', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={'ordering': ['-submitted_at']},
        ),
        migrations.CreateModel(
            name='PreAssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MT', 'MT (L11 | Band 4)'), ('GET', 'GET (L08T | Band 5)')], max_length=10)),
                ('rater_type', models.CharField(choices=[('candidate', 'Candidate'), ('manager', 'Manager')], max_length=20)),
                ('employee_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('role_grade', models.CharField(blank=True, max_length=100)),
                ('dept', models.CharField(blank=True, max_length=200)),
                ('manager_name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('competency_ratings', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={'ordering': ['-submitted_at']},
        ),
        migrations.CreateModel(
            name='PostAssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MT', 'MT (L11 | Band 4)'), ('GET', 'GET (L08T | Band 5)')], max_length=10)),
                ('rater_type', models.CharField(choices=[('candidate', 'Candidate'), ('manager', 'Manager')], max_length=20)),
                ('employee_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('training_completed', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField()),
                ('manager_name', models.CharField(blank=True, max_length=200)),
                ('days_since_training', models.IntegerField(blank=True, null=True)),
                ('competency_ratings', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={'ordering': ['-submitted_at']},
        ),
        migrations.CreateModel(
            name='BARSTechnicalResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MT', 'MT (L11 | Band 4)'), ('GET', 'GET (L08T | Band 5)')], max_length=10)),
                ('employee_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('obs_number', models.CharField(choices=[('30', '30 Days'), ('60', '60 Days'), ('90', '90 Days')], max_length=10)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('supervisor', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('ratings', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={'ordering': ['-submitted_at']},
        ),
        migrations.CreateModel(
            name='BARSBehaviouralResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MT', 'MT (L11 | Band 4)'), ('GET', 'GET (L08T | Band 5)')], max_length=10)),
                ('employee_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('obs_number', models.CharField(choices=[('30', '30 Days'), ('60', '60 Days'), ('90', '90 Days')], max_length=10)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('supervisor', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('ratings', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={'ordering': ['-submitted_at']},
        ),
        migrations.CreateModel(
            name='BARSLeadershipResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MT', 'MT (L11 | Band 4)'), ('GET', 'GET (L08T | Band 5)')], max_length=10)),
                ('employee_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('obs_number', models.CharField(choices=[('30', '30 Days'), ('60', '60 Days'), ('90', '90 Days')], max_length=10)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('supervisor', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('ratings', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={'ordering': ['-submitted_at']},
        ),
    ]
